export const colors = {
    page: '#F2F2F5',
    sheet: '#FFFFFF',
    navBar: '#EBEBEB',
    surface: '#FFFFFF',
    surfaceMuted: '#EBEBEB',
    accent: '#F49F99',
    accentWash: '#FDECEB',
    ink: '#000000',
    inkSecondary: '#8A8A8E',
    navInk: '#828286',
    navPill: '#EDDCDB',
    wheelInk: '#A6A6AA',
    doneInk: '#59595F',
};
export const fontFamily = {
    text: 'RobotoText',
    gutter: 'RobotoGutter',
    now: 'RobotoNow',
    note: 'RobotoNote',
    number: 'RobotoNumber',
    title: 'RobotoTitle',
    header: 'RobotoHeader',
    sub: 'RobotoSub',
    action: 'RobotoAction',
    setting: 'RobotoSetting',
    chip: 'RobotoChip',
    more: 'RobotoMore',
};
export const type = {
    header: { fontSize: 23.0, fontFamily: fontFamily.header, lineHeight: 28 },
    rowTitle: { fontSize: 18.7, fontFamily: fontFamily.title, lineHeight: 21.09, letterSpacing: 0.15 },
    rowTitleTall: { fontSize: 18.7, fontFamily: fontFamily.title, lineHeight: 21.64, letterSpacing: 0.15 },
    rowSub: { fontSize: 12.8, fontFamily: fontFamily.text, lineHeight: 14.18, letterSpacing: 0.08 },
    rowMeta: { fontSize: 12.6, fontFamily: fontFamily.text, lineHeight: 14.18, letterSpacing: 0.08 },
    note: { fontSize: 13.2, fontFamily: fontFamily.note, lineHeight: 16, letterSpacing: 0.3 },
    navLabel: { fontSize: 13.0, fontFamily: fontFamily.text, lineHeight: 16, letterSpacing: 0.08 },
    gutter: { fontSize: 10.23, fontFamily: fontFamily.gutter, lineHeight: 12, letterSpacing: 1.0 },
    count: { fontSize: 12.6, fontFamily: fontFamily.text, lineHeight: 14.18, letterSpacing: 0.08 },
    dayLabel: { fontSize: 12.6, fontFamily: fontFamily.text, lineHeight: 14.18 },
    dayNumber: { fontSize: 16.8, fontFamily: fontFamily.number, lineHeight: 18.91 },
    gutterNow: { fontSize: 10.23, fontFamily: fontFamily.now, lineHeight: 12, letterSpacing: 1.0 },
};
export const frame = {
    width: 392.73,
    height: 777.45,
};
export const space = {
    header: {
        titleLeft: 16,
        titleTop: 17.82,
        titleHeight: 28,
        titleAccentFrom: 114.9,
        titleAccentTo: 169,
        calendarsLeft: 340.73,
        calendarsTop: 8,
        button: 48,
    },
    sheet: { top: 150.18, radius: 22 },
    navBar: { top: 713.45, height: 64 },
    week: {
        labelTop: 65,
        labelHeight: 14.18,
        numberTop: 86.91,
        numberBox: 18.91,
        badgeTop: 122.18,
        badge: 8,
        badgeDisc: 13.82,
        glyph: 7.2,
        columnPitch: 53.82,
        firstColumnLeft: 8,
    },
    nav: {
        iconTop: 723.64,
        icon: 24,
        labelTop: 755.64,
        labelHeight: 16,
        pill: { w: 55.64, h: 31.64, top: 719.64 },
    },
    fab: { cx: 348.73, cy: 669.45, diameter: 56 },
    disc: { cx: 82.18, diameter: 60.5, diameterTall: 76.5 },
    ring: { cx: 368.91, outer: 22.18, stroke: 2.18 },
    textLeft: 128,
    connector: { dash: 5.45, gap: 5.45, width: 2.18 },
};
